export const countryFlagMap: { [key: string]: string } = {
  ARS: "AR",
  AUD: "AU",
  BRL: "BR",
  CAD: "CA",
  CLP: "CL",
  CNY: "CN",
  CZK: "CZ",
  DKK: "DK",
  EUR: "EU",
  GBP: "GB",
  HKD: "CN",
  HRK: "HR",
  HUF: "HU",
  INR: "IN",
  ISK: "IS",
  JPY: "JP",
  KRW: "KR",
  NZD: "NZ",
  PLN: "PL",
  RON: "RO",
  RUB: "RU",
  SEK: "SE",
  SGD: "SG",
  THB: "TH",
  TRY: "TR",
  TWD: "TW",
  USD: "US",
};

export const BTCStatisticMap = {
  marketcap: {
    title: "Market Cap",
    unit: "USD",
  },
  totalbc: {
    title: "Total Bitcoin",
    unit: "BTC",
  },
  "24hrtransactioncount": { title: "Transactions last 24h", unit: "" },
  "24hrbtcsent": { title: "BTC sent last 24h", unit: "BTC" },
  hashrate: { title: "Hashrate", unit: "GH/s" },
  getdifficulty: { title: "Difficulty", unit: "T" },
};
