export const countryFlagMap: { [key: string]: string } = {
  ARS: "AR",
  AUD: "AU",
  BRL: "BR",
  CAD: "CA",
  CLP: "CL",
  CNY: "CN",
  CZK: "CZ",
  DKK: "DK",
  EUR: "EU",
  GBP: "GB",
  HKD: "CN",
  HRK: "HR",
  HUF: "HU",
  INR: "IN",
  ISK: "IS",
  JPY: "JP",
  KRW: "KR",
  NZD: "NZ",
  PLN: "PL",
  RON: "RO",
  RUB: "RU",
  SEK: "SE",
  SGD: "SG",
  THB: "TH",
  TRY: "TR",
  TWD: "TW",
  USD: "US",
};

export const BTCStatisticMap  = {
  marketcap: 'Market Cap',
  totalbc: 'Total Bitcoin',
  "24hrtransactioncount": 'Transactions last 24h',
  "24hrbtcsent": 'BTC sent last 24h',
  hashrate: 'Hashrate',
  getdifficulty: 'Difficulty',
}